version: '3'

services:
  
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
  
  web:
    build: .
    command: >- 
      bash -c "python manage.py makemigrations && 
      python manage.py migrate --noinput && 
      gunicorn --env DJANGO_SETTINGS_MODULE=judge.settings -w 4 judge.wsgi:application"
    volumes:
      - .:/backend
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    command: celery -A judge worker -l info
    volumes:
      - .:/backend
    depends_on:
      - redis
      - db 
      - web

  frontend:
    build: ./website
    command: bash -c "npm run start"
    env_file: 
      .frnt.env
    ports:
      - "3000:3000"

volumes:
  postgres_data: