version: '3.3'

services:
  
  db:
    image: postgres:12
    env_file: 
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      .env
  
  backend:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: >- 
      bash -c "python manage.py makemigrations &&
      python manage.py makemigrations interface && 
      python manage.py migrate --noinput && 
      python manage.py migrate --noinput interface && 
      python manage.py collectstatic --no-input &&
      python manage.py loaddata /backend/language_model.json &&
      gunicorn judge.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./:/backend:rw
      - ./static:/backend/static/
      - ./media:/backend/media/
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
  
  nginx:
    build: ./nginx
    volumes:
      - ./static:/backend/static/
      - ./media:/backend/media/
    ports:
      - "80:80"
    depends_on:
      - backend
  
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./fstatic:/frontend/_next/static/
      - ./fmedia:/frontend/_next/media/
    depends_on:
      - backend

volumes:
  postgres_data:
