version: '3'

services:
  
  db:
    image: postgres:12
    env_file: 
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
  
  backend:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: >- 
      bash -c "python manage.py makemigrations --settings=judge.dev_settings &&
      python manage.py makemigrations --settings=judge.dev_settings interface && 
      python manage.py migrate --noinput --settings=judge.dev_settings && 
      python manage.py migrate --noinput --settings=judge.dev_settings interface && 
      python manage.py loaddata --settings=judge.dev_settings language_models.json &&
      python manage.py runserver 0.0.0.0:8000 --settings=judge.dev_settings"
    volumes:
      - app:/backend:rw
      - static:/backend/static/
      - media:/backend/media/
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  executor:
    image: phantsure/oj:latest
    working_dir: /OJExec-Python/
    command: celery -A tasks worker -l info
    depends_on:
      - redis
      - db 
      - backend

  frontend:
    build: ./frontend
    command: npm run dev
    env_file: 
      ./frontend/.env
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  app:
  static:
  media: