
// CONTEST FETCING ACTIONS
export const CONTEST_REQUEST_PENDING = "CONTEST_REQUEST_PENDING";
export const CONTEST_DATA_SUCCESS = "CONTEST_DATA_SUCCESS";
export const CONTEST_DATA_FAILURE = "CONTEST_DATA_FAILURE";

export const LEADERBOARD_REQUEST_PENDING = "LEADERBOARD_REQUEST_PENDING";
export const LEADERBOARD_DATA_FAILURE = "LEADERBOARD_DATA_FAILURE";
export const LEADERBOARD_DATA_SUCCESS = "LEADERBOARD_DATA_SUCCESS";

//Personal Submissions fetching actions
export const PERSONAL_SUBMISSIONS_REQUEST_PENDING = "PERSONAL_SUBMISSIONS_REQUEST_PENDING";
export const PERSONAL_SUBMISSIONS_DATA_FAILURE = "PERSONAL_SUBMISSIONS_DATA_FAILURE";
export const PERSONAL_SUBMISSIONS_DATA_SUCCESS = "PERSONAL_SUBMISSIONS_DATA_SUCCESS";

//Submissions fetching actions
export const SUBMISSIONS_REQUEST_PENDING = "SUBMISSIONS_REQUEST_PENDING";
export const SUBMISSIONS_DATA_FAILURE = "SUBMISSIONS_DATA_FAILURE";
export const SUBMISSIONS_DATA_SUCCESS = "SUBMISSIONS_DATA_SUCCESS";

//Questions fetching actions
export const QUESTIONS_REQUEST_PENDING = "QUESTIONS_REQUEST_PENDING";
export const QUESTIONS_DATA_FAILURE = "QUESTIONS_DATA_FAILURE";
export const QUESTIONS_DATA_SUCCESS = "QUESTIONS_DATA_SUCCESS";

//Editorial fetching actions
export const EDITORIAL_REQUEST_PENDING = "EDITORIAL_REQUEST_PENDING";
export const EDITORIAL_DATA_FAILURE = "EDITORIAL_DATA_FAILURE";
export const EDITORIAL_DATA_SUCCESS = "EDITORIAL_DATA_SUCCESS";

//Individual Question fetching actions
export const INDI_QUES_REQUEST_PENDING = "INDI_QUES_REQUEST_PENDING";
export const INDI_QUES_DATA_FAILURE = "INDI_QUES_DATA_FAILURE";
export const INDI_QUES_DATA_SUCCESS = "INDI_QUES_DATA_SUCCESS";