export const CONTEST_REQUEST_PENDING = "CONTEST_REQUEST_PENDING"

// CONTEST FETCING ACTIONS
export const CONTEST_DATA_PENDING = "CONTEST_DATA_PENDING";
export const CONTEST_DATA_SUCCESS = "CONTEST_DATA_SUCCESS";
export const CONTEST_DATA_FAILURE = "CONTEST_DATA_FAILURE";