# Generated by Django 3.0.6 on 2020-05-04 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_answers', models.IntegerField(default=0, help_text='Number of WAs for the user here')),
                ('time_out', models.IntegerField(default=0, help_text='Number of TLEs for the user here')),
                ('score', models.IntegerField(default=0, help_text='Score of the user')),
                ('correct_answers', models.IntegerField(default=0, help_text='Number of correct answers of the user')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, help_text='To check the least time taken for a common score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
