# Generated by Django 3.0.6 on 2020-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coder',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name of the user', max_length=50),
        ),
        migrations.AddField(
            model_name='coder',
            name='image_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='coder',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the user here', max_length=50),
        ),
        migrations.AddField(
            model_name='coder',
            name='solved_ques',
            field=models.CharField(blank=True, help_text='Questions solved by the user', max_length=200),
        ),
    ]
