# Generated by Django 3.0.5 on 2020-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, help_text='The entire text for the question')),
                ('question_image', models.ImageField(blank=True, help_text='Optional Image if the question demands', upload_to='')),
                ('input_example', models.TextField(blank=True, help_text='Example showing how should the input look')),
                ('output_example', models.TextField(blank=True, help_text='Example showing how should the output look')),
            ],
        ),
    ]
