# Generated by Django 3.0.5 on 2020-05-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coder',
            old_name='wrong_answer',
            new_name='wrong_answers',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Answer field for the questions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Question')),
            ],
        ),
    ]
