# Generated by Django 3.0.6 on 2020-05-04 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20200504_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time and Date the contest starts')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time and Date the contest ends')),
            ],
        ),
    ]
