# Generated by Django 3.0.6 on 2020-05-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coder',
        ),
    ]
