# Generated by Django 3.0.6 on 2020-05-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_delete_coder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_test', models.TextField(blank=True, help_text='Input test case')),
                ('output_test', models.TextField(blank=True, help_text='Output test case')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Question')),
            ],
        ),
    ]
