# Generated by Django 3.0.6 on 2020-05-12 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0008_auto_20200512_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_memory_limit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_time_limit',
        ),
        migrations.AddField(
            model_name='question',
            name='memory_limit',
            field=models.IntegerField(default=100000, help_text='Memory limit for the question'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=1, help_text='Time limit for the question'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, help_text="Status in json format. Please don't touch it.")),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
