# Generated by Django 3.0.6 on 2020-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20200514_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='AC_no',
            field=models.IntegerField(default=0, help_text='Number of correct answers for this job'),
        ),
        migrations.AddField(
            model_name='job',
            name='WA_no',
            field=models.IntegerField(default=0, help_text='Number of wrong answers for this job'),
        ),
    ]
