# Generated by Django 3.0.6 on 2020-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20200514_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(help_text='Celery Job id for the current task', max_length=200, null=True, unique=True),
        ),
    ]
