# Generated by Django 3.0.6 on 2020-05-17 04:42

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='output_test',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
