# Generated by Django 3.0.6 on 2020-05-17 04:57

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_auto_20200517_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='output_test',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
