# Generated by Django 3.0.6 on 2020-05-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_auto_20200517_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='output_test',
            field=models.TextField(blank=True),
        ),
    ]
