# Generated by Django 3.0.6 on 2020-05-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_auto_20200517_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='output_test',
            field=models.TextField(blank=True, help_text='Output test case'),
        ),
    ]
